debug: true
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.219.128:3306/master_program
    #    initialize: true
    #    sql-script-encoding: UTF-8
    username: master_program_account
    password: aBgjigvm,jovm,t/
    tomcat:
      validation-query: SELECT 1;
      initial-size: 20
      max-active: 80
      max-idle: 60
      min-idle: 20
      max-wait: 3000
      test-on-borrow:  false
      test-on-return: true

  jpa:
    database: mysql
    hibernate:
      order_inserts: true
      order_updates: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

