/*
 * This file is generated by jOOQ.
*/
package lanyao.springsecurity.oauth.domain;


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lanyao.springsecurity.oauth.View;
import lanyao.springsecurity.oauth.jackson.HexBase32Des;
import lanyao.springsecurity.oauth.jackson.HexBase32Ser;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;


/**
 * 語言
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "language", schema = "master_program")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "id")
public class Language implements Serializable {

    private static final long serialVersionUID = -10766837;

    private Integer id;
    private String  abbreviation;
    private String  name;
    private Integer languageOrder;
    private byte[]  uuid;


    private List<NewsKind> newsKinds;

    public Language() {}

    public Language(Language value) {
        this.id = value.id;
        this.abbreviation = value.abbreviation;
        this.name = value.name;
        this.languageOrder = value.languageOrder;
        this.uuid = value.uuid;
    }

    public Language(
        Integer id,
        String  abbreviation,
        String  name,
        Integer languageOrder,
        byte[]  uuid
    ) {
        this.id = id;
        this.abbreviation = abbreviation;
        this.name = name;
        this.languageOrder = languageOrder;
        this.uuid = uuid;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    @NotNull
    @JsonView({View.NewsKind.class})
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "abbreviation", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    @JsonView({View.NewsKind.class})
    public String getAbbreviation() {
        return this.abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    @Column(name = "name", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    @JsonView({View.NewsKind.class})
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "language_order", nullable = false, precision = 10)
    @NotNull
    public Integer getLanguageOrder() {
        return this.languageOrder;
    }

    public void setLanguageOrder(Integer languageOrder) {
        this.languageOrder = languageOrder;
    }

    @Column(name = "uuid", nullable = false, length = 16)
    @NotNull
    @JsonSerialize(using = HexBase32Ser.class)
    @JsonView({View.NewsKind.class})
    public byte[] getUuid() {
        return this.uuid;
    }

    @JsonDeserialize(using = HexBase32Des.class)
    public void setUuid(byte... uuid) {
        this.uuid = uuid;
    }


//    ======================

    @OneToMany(mappedBy = "language",fetch = FetchType.LAZY)
    public List<NewsKind> getNewsKinds() {
        return newsKinds;
    }

    public void setNewsKinds(List<NewsKind> newsKinds) {
        this.newsKinds = newsKinds;
    }

}
