/*
 * This file is generated by jOOQ.
*/
package lanyao.springsecurity.oauth.domain;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lanyao.springsecurity.oauth.SystemConstant;
import lanyao.springsecurity.oauth.auditable.BaseAuditable;
import lanyao.springsecurity.oauth.form.LabelForm;
import lanyao.springsecurity.oauth.jackson.HexBase32Des;
import lanyao.springsecurity.oauth.jackson.HexBase32Ser;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 消息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
//@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class,property = "@id")
@Table(name = "news", schema = "master_program")
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class News extends BaseAuditable implements Serializable {

    private static final long serialVersionUID = -52888524;

    private Integer       id;

    private String        title;

    private String        content;

    private String        status;

    private LocalDateTime releaseDate;
    private byte[]        uuid;

    private NewsKind newsKind;



    private LabelForm statusForm;
    private String releaseDateYyyyMmDd;

    @Override
    public boolean equals(Object o) {
        News news = (News) o;
        return this.id.intValue()==news.id.intValue();
    }

    public News() {}
    public News(Integer newsId){
        this.id = newsId;
    }

    public News(News value) {
        this.id = value.id;
        this.title = value.title;
        this.content = value.content;
        this.status = value.status;
        this.releaseDate = value.releaseDate;
        this.uuid = value.uuid;
    }

    public News(
        Integer       id,
        String        title,
        String        content,
        String        status,
        LocalDateTime releaseDate,
        byte[]        uuid
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.status = status;
        this.releaseDate = releaseDate;
        this.uuid = uuid;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "title", nullable = false, length = 180)
    @NotNull
    @Size(max = 180)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "content", nullable = false)
    @NotNull
    @Lob
    @Basic(fetch = FetchType.LAZY)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "status", nullable = false, length = 2)
    @NotNull
    @Size(max = 2)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "release_date", nullable = false)
    @NotNull
    @JsonFormat(pattern = SystemConstant.Constants.DATE_ALL_FORMAT,timezone = SystemConstant.Constants.GMT_8)
    public LocalDateTime getReleaseDate() {
        return this.releaseDate;
    }

    public void setReleaseDate(LocalDateTime releaseDate) {
        this.releaseDate = releaseDate;
    }



    @Column(name = "uuid", nullable = false, length = 16)
    @NotNull
    @JsonSerialize(using = HexBase32Ser.class)
    public byte[] getUuid() {
        return this.uuid;
    }

    @JsonDeserialize(using = HexBase32Des.class)
    public void setUuid(byte... uuid) {
        this.uuid = uuid;
    }


//    =============================

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "kind_id")
    public NewsKind getNewsKind() {
        return newsKind;
    }

    public void setNewsKind(NewsKind newsKind) {
        this.newsKind = newsKind;
    }


    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Transient
    public LabelForm getStatusForm() {
        return statusForm;
    }

    public void setStatusForm(LabelForm statusForm) {
        this.statusForm = statusForm;
    }

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Transient
    public String getReleaseDateYyyyMmDd() {
        return releaseDateYyyyMmDd;
    }

    public void setReleaseDateYyyyMmDd(String releaseDateYyyyMmDd) {
        this.releaseDateYyyyMmDd = releaseDateYyyyMmDd;
    }
}
