/*
 * This file is generated by jOOQ.
*/
package lanyao.springsecurity.oauth.domain;


import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lanyao.springsecurity.oauth.View;
import lanyao.springsecurity.oauth.auditable.BaseAuditable;
import lanyao.springsecurity.oauth.jackson.HexBase32Des;
import lanyao.springsecurity.oauth.jackson.HexBase32Ser;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;


/**
 * 消息種類
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
//@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class,property = "@id")
@Table(name = "news_kind", schema = "master_program")
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class NewsKind extends BaseAuditable implements Serializable {

    private static final long serialVersionUID = -531505555;


    private Integer       id;


    private String        label;
    private Integer       kindOrder;
    private byte[]        uuid;



    private Language language;
    private List<News> news;



    public NewsKind() {}

    public NewsKind(Integer id){
        this.id = id;
    }

    public NewsKind(NewsKind value) {
        this.id = value.id;
        this.label = value.label;
        this.kindOrder = value.kindOrder;
        this.uuid = value.uuid;
    }

    public NewsKind(
        Integer       id,
        String        label,
        Integer       kindOrder,
        byte[]        uuid
    ) {
        this.id = id;
        this.label = label;
        this.kindOrder = kindOrder;
        this.uuid = uuid;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    @JsonView({View.NewsKind.class})
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "label", nullable = false, length = 30)
    @NotNull
    @Size(max = 30)
    @JsonView({View.NewsKind.class})
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Column(name = "kind_order", nullable = false, precision = 10)
    @NotNull
    @JsonView({View.NewsKind.class})
    public Integer getKindOrder() {
        return this.kindOrder;
    }

    public void setKindOrder(Integer kindOrder) {
        this.kindOrder = kindOrder;
    }


    @Column(name = "uuid", nullable = false, length = 16)
    @NotNull
    @JsonSerialize(using = HexBase32Ser.class)
    @JsonView({View.NewsKind.class})
    public byte[] getUuid() {
        return this.uuid;
    }

    @JsonDeserialize(using = HexBase32Des.class)
    public void setUuid(byte... uuid) {
        this.uuid = uuid;
    }






//    =====================

    @ManyToOne()
    @JoinColumn(name = "language_id")
    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    @OneToMany(mappedBy = "newsKind",cascade = {CascadeType.REMOVE},fetch = FetchType.LAZY)
    public List<News> getNews() {
        return news;
    }

    public void setNews(List<News> news) {
        this.news = news;
    }
}
