/*
 * This file is generated by jOOQ.
*/
package lanyao.springsecurity.oauth.domain;


import lanyao.springsecurity.oauth.auditable.BaseAuditable;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "role", schema = "master_program")
public class Role extends BaseAuditable implements Serializable {

    private static final long serialVersionUID = -1677143553;

    private Integer       id;
    private String        name;






    private List<UserRole> userRoles;







    public Role() {}

    public Role(Integer id) {
        this.id = id;
    }

    public Role(Role value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Role(
        Integer       id,
        String        name
    ) {
        this.id = id;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }



//    ================

    @OneToMany(mappedBy = "role",cascade = {CascadeType.REMOVE})
    public List<UserRole> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(List<UserRole> userRoles) {
        this.userRoles = userRoles;
    }
}
